CREATE TABLE public.ordem_servico
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    data_abertura timestamp without time zone,
    data_finalizacao timestamp without time zone,
    descricao character varying(255) COLLATE pg_catalog."default",
    preco numeric(19,2),
    status character varying(255) COLLATE pg_catalog."default",
    cliente_id bigint,
    CONSTRAINT ordem_servico_pkey PRIMARY KEY (id),
    CONSTRAINT fkbgbo9jhvq1cuycsv5tvynn1ig FOREIGN KEY (cliente_id)
        REFERENCES public.cliente (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.ordem_servico
    OWNER to postgres;